
***

# Calcul Matriciel
## TP6. Matching, Weddings and cie
***
***

In this practical, we are going to solve the perfect marriage  problem and implement Gale-Shapley algorithm, used to pair two populations based on each agent's preferences


***
***
A few ground rules for your report:
* _your code must be clear, commented and use explicit variable names_
* _every algorithm must be tested on a few examples which show the different use cases_
* _markdown comments and examples must be provided, and the report should be self-contained_

In [37]:
import networkx as nx
import numpy as np
import random as rd
import matplotlib.pyplot as plt
%matplotlib inline
#magic
import warnings
warnings.filterwarnings('ignore')


***
## <font color=blue>Stable mariages</font>
***

***

### _modelization of the problem_

the students and unis are represented by interger ranging from $0$ to $n-1$.

The preferences are given by two np array of shape $(n,n)$, <tt>prefStu</tt> and <tt>prefUni</tt> thus the preferences of student $i$ are given by <tt>prefStu[i]</tt>.

The marriages are going to be stored in the adjacency matrix $M$ of a (bipartite) graph whose vertices are students (numbered $0$ to $n-$) and unis (numbered $n+0$ to $n+n-1$).



**To Do:**

**_question 1_**

**a** Given arrays of $n$  students/universities, create a array of array for the preferences of each student/university (to have an example for next questions).



**b** using <tt>np.arange(n)</tt>, and <tt>np.random.permutation(a)</tt> ; create a random matrix of preferences of size $n \times n$.


**c** 
Write a function which determines weither a student (resp. a university) is married and to whom (use <tt>np.where</tt> for instance).


**d**
Write a function which determines if a university prefers a proposed marriage other its current one
Same thing for a student.


**d'** 
_(optional)_ Write a function which determines weither a marriage is stable or not.




One can compare and verify the solution using https://daffidwilde.github.io/matching/docs/tutorials/stable_marriage.html

In [38]:
#a
def Students(size):
    Student = np.zeros((size,size))
    return Student

#b
def Liste(size):
    L=[]
    for i in range(size):L.append(i+1)
    rd.shuffle(L)
    return L

def Rand_pref(size):
    Etudiant = Students(size)
    for i in range(size):
        L = Liste(size)
        for j in range(size):
            Etudiant[i,j] = L[j]
    return Etudiant
        

print(Rand_pref(10))



[[10.  2.  8.  5.  9.  1.  3.  4.  6.  7.]
 [ 4.  6.  9.  7.  5.  2.  8.  1.  3. 10.]
 [ 8.  5.  1.  9.  2.  3.  7.  6. 10.  4.]
 [ 6.  3.  4.  2.  9.  8. 10.  1.  5.  7.]
 [ 4.  6.  7.  2.  8.  9.  1.  3. 10.  5.]
 [ 7.  8.  4.  1.  5.  6.  2. 10.  3.  9.]
 [10.  2.  3.  9.  4.  7.  1.  5.  8.  6.]
 [ 8. 10.  9.  4.  6.  5.  2.  3.  7.  1.]
 [ 9.  5.  6.  3.  1.  2.  7.  4. 10.  8.]
 [ 4.  9.  8.  1.  5.  7. 10.  2.  3.  6.]]


In [46]:
#c
def MatriceMariage(size):
    return np.zeros((size,2))

size = 12
M = MatriceMariage(size)

def IsMariedU(M,u):
    """
    #determines if and to whom uni u is matched in M 
    """ 
    return M[u,1]

    
def IsMariedS(M,s):
    """
    #determines if and to whom student s is matched in M 
    """    
    return M[s,0]


def IsCouple(M,s,u):
    """
    #determines if student s and uni u are matched in M
    """
    return u == M[u,0]


#d
def PrefersUni(M,prefUni,u,prop):
    """
    #determines if uni u prefers the proposition prop
    #to its current matching    
    """
    student = M[0,u]
    for i in range(student):
        if prefUni[student] == prop:
            M[0,u] = 0
            M[1,u] = prop
            M[0,prop] = u
            return M,
    return M    
#chec si tjr la même chose après, si oui rang +1 et try angain

def PrefersStu(M,prefStu,s,prop):
    """
    determines if student s prefers the proposition prop
    to its current matching      
    """
    university = M[1,s]
    for i in range(university):
        if prefStu[university] == prop :
            M[1,s] = 0
            M[0,s] = prop
            M[1,prop] = s
            return M
    return M
#chec si tjr la même chose après, si oui rang +1 et try angain

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 0.0


In [40]:
"""tests"""

'tests'

**_question 2_**

Assemble the previous functions to get the Gale-Shapley algorithm.

In [41]:
###todo
def Nilpotente(M):
    for i in range(np.shape(M)[0]):
        for j in range(np.shape(M)[1]):
            if M[i,j] == 0:
                return False
    return True

def GaleShapley(studentPref,uniPref,size):
    """
        Stable marriage

        :param studentPref:  preferences of students
        :type studentPref: np array of dim 2
        :param uniPref:  preferences of universities
        :type uniPref: np array of dim 2
        :return: Stable marriage (adjacency matrix of bipartite graph)
        :rtype: np array of dim 2
    """
    M = MatriceMariage(size)
    while(Nilpotente(M) == False):
        
        
    
           
    return M

**_bonus question 1_** 

Create a function ploting the marriages along the algorithm (idealy with dashed line and colours when a couple is broken)

**_bonus question 2_** 


Plot the average time of execution of the algorithm on (random) instances of size $n$.
Conjecture the average time complexity and compare to the (theoretical) worst case time complexity.

In [42]:
import time



**_bonus question 3_** 

Plot the average choice for student and uni on (random) instances of size $n$.

**_bonus question 4_** 

Implement and illustrate Irving stable roommates algorithm.